# -*- coding: utf-8 -*-
"""LRUPageReplacement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YCz25PzjNDXF94yBF6ckfxmxYKjezNIt
"""

buffer = int(input('Enter buffer size'))

sequence = list(map(int, input('Enter input sequence').split()))
buffer_ls = []  
page_fault = 0

  
for i in sequence: 
  

    if i in buffer_ls: 
         # Remove previous index of current page 
        print('--hit--')
        buffer_ls.remove(i) 
  
        # Now append it, at last index 
        buffer_ls.append(i) 
  

    else: 
        # Check if the list can hold equal pages 
        if(len(buffer_ls) == buffer): 
            buffer_ls.remove(buffer_ls[0]) 
            buffer_ls.append(i) 
  
        else: 
            buffer_ls.append(i) 
  
        print(buffer_ls)
        page_fault +=1

print('Number of page fault', page_fault)