# -*- coding: utf-8 -*-
"""Sjfc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TOSQ4qnig8_D0tLZKHLNfPSxPe-YazB

Shortest Job First
"""

processNum = int(input("Enter process number: "))
x=1
bursttime = []
cbursttime = []
d = []

for i in range(processNum):
  print("Process",x, end=': ')
  bursttime.append(int(input("Burst time= ")))
  x+=1
cbursttime = [None] * len(bursttime);    
     
  
for i in range(0, len(bursttime)):    
    cbursttime[i] = bursttime[i]; 
cbursttime.sort()

for i in range(0, len(bursttime)): 
    for j in range(0, len(bursttime)): 
        if(cbursttime[i]==bursttime[j]):
            d.append(j+1)  
print("\n")
waitTime = []
avgwaitTime = 0
waitTime.insert(0,0)

for j in range(1, len(cbursttime)):
  waitTime.insert(j, (waitTime[j-1] + cbursttime[j-1]))
  avgwaitTime += waitTime[j]

avgwaitTime = float(avgwaitTime / processNum)
print("The average waiting time will be = ",avgwaitTime,"ms")

print("\n")
for k in range(0, processNum):
  print(waitTime[k], "p"+str(d[k])," ",  end='')
  a=waitTime[len(waitTime)-1]
  b=cbursttime[len(cbursttime)-1]
  c=a+b
print(c)
print("This is the GANTT chart for the above process")

