# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v5Fja9XJMNZr_W7DLNDL0jpCcdi66edT

FCFS
"""

queue = list(map(int, input('Enter sequence : ').split()))
header = int(input('Give header : '))

queue.insert(0, header)


temp = [0]
print("Total Distance:")
for i in range(1,len(queue)):
    if i == len(queue)-1:
        print('({}-{})'.format(queue[i],queue[i-1]))
    else:
        print('({}-{})'.format(queue[i],queue[i-1]),end='+')
    temp.append(abs(queue[i]-queue[i-1]))

print("\n")
print('Path:',queue)
print("\n")
print('Illustration shows total head movement of',sum(temp),'cylinders')



