# -*- coding: utf-8 -*-
"""Fcfs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TOSQ4qnig8_D0tLZKHLNfPSxPe-YazB

First Come First Serve
"""

processNum = int(input("Enter process number: "))
x=1
brusttime = []

for i in range(processNum):
  print("Process",x, end=': ')
  brusttime.append(int(input("Burst time= ")))
  x=x+1
  
print("\n")
waitTime = []
avgwaitTime = 0
waitTime.insert(0,0)

for j in range(1, len(brusttime)):
  waitTime.insert(j, (waitTime[j-1] + brusttime[j-1]))
  avgwaitTime += waitTime[j]

avgwaitTime = float(avgwaitTime / processNum)
print("The average waiting time will be = ",avgwaitTime,"ms")

print("\n")
processNo = 1
for k in range(0, processNum):
  print(waitTime[k], "p"+str(processNo)," ",  end='')
  processNo += 1
  a=waitTime[len(waitTime)-1]
  b=brusttime[len(brusttime)-1]
  c=a+b
print(c)
print("This is the GANTT chart for the above process")

