# -*- coding: utf-8 -*-
"""Priorityscheduling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TOSQ4qnig8_D0tLZKHLNfPSxPe-YazB

Priority Scheduling
"""

def inputdata():
    processno = int(input('Enter process number: '));
    array = [];
    for x in range(0, processno):
        a = 'p' + str(x + 1);
        bursttime = int(input( a + ' Bursttime  ' +' : '));
        Priority = int(input( a + ' Priority ' +' : '));
        b = [a, bursttime,Priority];
        array.append(b);
    temp = [];
    for i in range(0, len(array) - 1):
        for j in range(0, len(array) - 1):
            if array[j][2] > array[j + 1][2]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j + 1] = temp
    return array,processno

def mainfunc(array,processno):
    time=0
    totaltime=0
    chart = ''
    chart2 = ''
    string=''
    for x in range(0,len(array)):
        time =time + array[x][1]
        chart=chart+array[x][0]
        if(x<len(array)-1):
            totaltime=totaltime+time
        string=string+' '+array[x][0]+' '+ str(time)
    print("\n")
    avgwaittime=totaltime/processno
    print('The average waiting time will be =  '+ str(avgwaittime)+' ms')
    print("\n")
    print('0'+string)
    print("This is the GANTT chart for the above process")

a,b=inputdata()
mainfunc(a,b)

