# -*- coding: utf-8 -*-
"""FIFO_Page_Replacement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBVvW8CYA2ywasxz5TEpE8KvqsomzUyg
"""

buffer = int(input('Enter buffer size'))

sequence = list(map(int, input('Enter input sequence').split()))
buffer_ls = []
page_fault = 0
for val in sequence:
    if len(buffer_ls)<buffer:
        if val in buffer_ls:
            print('--hit--')
        else:
            page_fault+=1
            buffer_ls.append(val)
            print(buffer_ls)
    else:
        if val in buffer_ls:
            print('--hit--')
        else:
            page_fault+=1
            buffer_ls.pop(0)
            buffer_ls.append(val)
            print(buffer_ls)



print('Number of page fault', page_fault)