# -*- coding: utf-8 -*-
"""Roundrobin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TOSQ4qnig8_D0tLZKHLNfPSxPe-YazB

Round Robin
"""

def myfuncin():
    processno = int(input('Enter process number: '));
    array = [];
    sum_of_burst_time = 0;
    index = [];
    sumwaittime=[];
    wtarray=[];
    for x in range(0, processno):
        index.append(0);
        process_no = 'p' + str(x + 1);
        burst_time = int(input('Bursttime ' + process_no + ': '));
        sum_of_burst_time = sum_of_burst_time +burst_time;
        single_process_array = [process_no, burst_time];
        pronostendwait=[process_no,0,0,0];
        pronowait=[process_no,0];
        array.append(single_process_array);
        wtarray.append(pronostendwait);
        sumwaittime.append(pronowait);
    Quantam = int(input('Quantam number : '));
    waittime=0;
    starttime=0;
    endtime=0;
    grntt_chart='0';
    x=0;
    while(sum_of_burst_time>x):
        for i in range(0,processno):
            starttime=x;
            for j in range(1, Quantam + 1):
                if array[i][1] >0:
                    x=x+1;
                    array[i][1] = array[i][1] - 1;
                else:
                    index[i]=index[i]+1;
            endtime = x
            if starttime != endtime:
                waittime=starttime-wtarray[i][2]
                sumwaittime[i][1]=int(sumwaittime[i][1])+int(waittime)
            wtarray[i][1]=starttime;
            wtarray[i][2]=endtime;
            wtarray[i][3]=waittime;
            if index[i]< Quantam+1:
                grntt_chart = grntt_chart + ' ' + array[i][0]
                grntt_chart=grntt_chart+' '+ str(x)
    avgwaittime=0;
    for m in range(0, processno):
        avgwaittime=avgwaittime+sumwaittime[m][1];
    avgwaittime=avgwaittime/processno
    print("\n")
    print('The average waiting time will be = ' + str(avgwaittime)+' ms')
    print("\n")
    print( grntt_chart)
    print("This is the GANTT chart for the above process")
myfuncin()

